import { useCallback, useEffect, useRef, useState } from 'react'
import { ArrowUpRight, BookOpen, ChartNoAxesColumnIncreasing, Check, ChevronDown, Database, FlaskConical, Layers, Menu, Moon, Network, Search, Sun, X } from 'lucide-react'
import ResearchMap from './ResearchMap'
import { PaperStory, PaperEvolution } from './PaperStory'
import DailyBrief from './DailyBrief'
import { papers, corePapers, groups, categories, taxonomy, relations, byId, categoryById, colorFor, matchesCategory, name, text, readable, statusLabel, years, type Paper } from './data'

const views = [{id:'timeline',label:'Timeline',icon:BookOpen},{id:'directions',label:'Technical Routes',icon:Layers},{id:'research-map',label:'Evolution Map',icon:Network},{id:'database',label:'Paper Library',icon:Database},{id:'daily-brief',label:'Daily Brief',icon:BookOpen},{id:'efficiency',label:'Inference Efficiency',icon:FlaskConical},{id:'systems',label:'Systems & Open Areas',icon:Network},{id:'statistics',label:'Statistics',icon:ChartNoAxesColumnIncreasing}]
export function PaperLinks({p}:{p:Paper}) {return <div className="paper-links">{(['Paper','Code','Project'] as const).map((label,i)=>{const url=[p.paper_url,p.code_url,p.project_url][i];return url?<a key={label} href={url} target="_blank" rel="noreferrer">{label}<ArrowUpRight size={13}/></a>:<span key={label}>{label}: N/A</span>})}</div>}
export function PaperCard({p,open}:{p:Paper;open:(p:Paper)=>void}) {return <article className="paper-card"><div className="flex items-start justify-between gap-3"><button className="paper-name" onClick={()=>open(p)}>{name(p)} <ArrowUpRight size={16}/></button><span className="mono muted">{text(p.year)}</span></div><PaperStory p={p}/><details className="inline-notes"><summary>Contribution · 主要贡献</summary><p>{p.main_contribution ?? 'N/A'}</p></details><PaperEvolution p={p} open={open}/><div className="card-meta"><span>{statusLabel(p)} · {text(p.venue)}</span>{!p.verified&&<span className="uncertain">待核实</span>}{p.scope==='context_only'&&<span>离散背景</span>}</div><PaperLinks p={p}/></article>}
function PaperDetail({p,close,open}:{p:Paper;close:()=>void;open:(p:Paper)=>void}) {
  const dialog = useRef<HTMLDialogElement>(null)
  useEffect(()=>{const el=dialog.current;const prev=document.activeElement as HTMLElement|null;el?.showModal();document.body.style.overflow='hidden';return()=>{el?.close();document.body.style.overflow='';prev?.focus()}},[])
  useEffect(()=>{dialog.current?.scrollTo(0,0)},[p.id])
  const fields: [string,unknown][]=[['首次公开年份',p.year],['首次公开日期',p.first_submission_date],['Venue',p.venue],['正式发表年份',p.publication_year],['状态',statusLabel(p)],['State space',readable(p.state_space)],['Representation unit',readable(p.representation_unit)],['Generation',readable(p.generation_type)],['Decoder',readable(p.decoder_type)],['Time parameterization',readable(p.time_parameterization)],['Model scale',p.model_scale?.label],['Inference focus',readable(p.inference_focus)],['Evaluation metrics',p.evaluation_metrics]]
  return <dialog ref={dialog} className="detail-dialog" onCancel={e=>{e.preventDefault();close()}} onClick={e=>{if(e.target===e.currentTarget)close()}} aria-labelledby="paper-detail-title"><div className="detail-content"><div className="detail-top"><span className="eyebrow">PAPER RECORD / {p.id}</span><button onClick={close} className="icon-button" aria-label="关闭论文详情"><X/></button></div><h2 id="paper-detail-title">{name(p)}</h2><p className="paper-full-title">{p.title}</p><p className="muted authors">{text(p.authors)}</p><div className="detail-status"><span className={p.verified?'verified':'uncertain'}>{p.verified?<Check size={14}/>:null}{p.verified?'核心信息已核实':'存在核实冲突'} · verified: {String(p.verified)}</span>{p.scope==='context_only'&&<span className="badge">离散背景 · context only</span>}</div><PaperLinks p={p}/><div className="detail-tags">{p.categories.map(c=><span key={c} style={{borderColor:colorFor(c),color:colorFor(c)}}>{categoryById[c]?.label??c}</span>)}</div>
    {[['Motivation / Problem · 研究问题',p.main_problem],['Solution · 解决方法',p.method_summary],['Contribution · 主要贡献',p.main_contribution]].map(([label,v])=><section className="detail-section" key={label}><h3>{label}</h3><p>{v??'N/A'}</p></section>)}
    <dl className="metadata-grid">{fields.map(([label,v])=><div key={label}><dt>{label}</dt><dd>{text(v)}</dd></div>)}</dl>
    <section className="detail-section"><h3>Efficiency mechanisms</h3>{p.efficiency_mechanism?Object.entries(p.efficiency_mechanism).map(([k,v])=><p key={k}><strong>{readable(k)}：</strong>{text(v)}</p>):<p>N/A</p>}</section>
    <section className="detail-section"><h3>Systems evidence</h3>{p.systems_evidence?<dl className="evidence-data">{Object.entries(p.systems_evidence).map(([k,v])=><div key={k}><dt>{readable(k)}</dt><dd>{k==='source'?<a href={String(v)} target="_blank" rel="noreferrer">原始来源 ↗</a>:text(v)}</dd></div>)}</dl>:<p>N/A</p>}</section>
    {p.model_scale&&<details className="detail-section"><summary>模型规模：范围与来源</summary><pre>{text(p.model_scale)}</pre></details>}
    <section className="uncertainty-box"><h3>Uncertainty & verification</h3><p>{p.verification_note}</p><small>{p.verification_level}</small><ul>{p.pending_verification.map((n,i)=><li key={i}>{n}</li>)}</ul></section>
    <section className="detail-section"><h3>研究关系</h3>{relations.filter(r=>r.source===p.id||r.target===p.id).map(r=><div className="relation-row" key={r.id}><button onClick={()=>open(byId[r.source===p.id?r.target:r.source])}>{name(byId[r.source])} → {name(byId[r.target])}</button><span>{readable(r.type)} · {r.evidence_level==='explicit'?'直接证据':'编辑性演化'}</span><p>{r.rationale}</p></div>)}{!relations.some(r=>r.source===p.id||r.target===p.id)&&<p>N/A</p>}</section>
    <section className="detail-section"><h3>Verification sources</h3>{p.verification_sources.map((s,i)=><div className="source-item" key={`${s.url}-${i}`}><a href={s.url} target="_blank" rel="noreferrer">{readable(s.type)} <ArrowUpRight size={14}/></a><p>{text(s.locator)}</p><small>{text(s.supports)} · {s.accessed_at}</small><small>URL check: {text(s.url_check?.status)} · {text(s.url_check?.checked_at)}</small></div>)}</section>
  </div></dialog>
}

export default function App() {
  const [view,setView]=useState(()=>views.some(v=>v.id===location.hash.slice(1))?location.hash.slice(1):'timeline')
  const [category,setCategory]=useState('all');const [query,setQuery]=useState('');const [year,setYear]=useState('all');const [state,setState]=useState('all');const [focus,setFocus]=useState('all')
  const [context,setContext]=useState(false);const [selected,setSelected]=useState<Paper|null>(null);const [mobileNav,setMobileNav]=useState(false)
  const [dark,setDark]=useState(()=>document.documentElement.dataset.theme==='dark')
  const [extra,setExtra]=useState<React.ComponentType<{view:string;items:Paper[];open:(p:Paper)=>void}>|null>(null)
  const open=useCallback((p:Paper)=>setSelected(p),[])
  useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';try{localStorage.setItem('atlas-theme',dark?'dark':'light')}catch{}},[dark])
  useEffect(()=>{const fn=()=>setView(views.some(v=>v.id===location.hash.slice(1))?location.hash.slice(1):'timeline');window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn)},[])
  function navigate(id:string){setView(id);location.hash=id;setMobileNav(false);window.scrollTo({top:0})}
  const allItems=context?papers:corePapers
  const searchItems=allItems.filter(p=>!query.trim()||[p.title,...p.alias,...p.authors,p.main_problem,p.main_contribution,p.method_summary,...p.tags].join(' ').toLowerCase().includes(query.trim().toLowerCase()))
  const filtered=searchItems.filter(p=>matchesCategory(p,category)&&(year==='all'||String(p.year)===year)&&(state==='all'||p.state_space===state)&&(focus==='all'||p.inference_focus===focus))
  const activeView=views.find(v=>v.id===view)!
  useEffect(()=>{document.title=`${activeView.label} · Continuous dLLM Atlas`},[activeView.label])
  function reset(){setQuery('');setCategory('all');setYear('all');setState('all');setFocus('all')}
  useEffect(()=>{if(!['research-map','database','daily-brief'].includes(view))import('./Sections').then(m=>setExtra(()=>m.default))},[view])
  const Extra=extra
  return <><a className="skip-link" href="#main-content">跳至内容</a><header className="site-header"><a className="brand" href="#timeline" onClick={()=>navigate('timeline')}><span className="brand-symbol">∿</span><span>Continuous <b>dLLM</b><small>RESEARCH ATLAS</small></span></a><nav className="top-nav" aria-label="主要视图">{views.map(v=><a key={v.id} href={`#${v.id}`} className={view===v.id?'active':''} onClick={()=>navigate(v.id)}>{v.label}</a>)}</nav><div className="header-end"><span className="snapshot">DATA SNAPSHOT <b>{taxonomy.updated_at}</b></span><button className="icon-button" onClick={()=>setDark(!dark)} aria-label={dark?'切换浅色模式':'切换深色模式'}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button><button className="icon-button mobile-menu" aria-label="打开导航" aria-expanded={mobileNav} onClick={()=>setMobileNav(!mobileNav)}>{mobileNav?<X/>:<Menu/>}</button></div></header>
    <div className="app-layout"><aside className={`sidebar ${mobileNav?'show':''}`}><nav className="side-views" aria-label="所有模块">{views.map(v=><button key={v.id} onClick={()=>navigate(v.id)} className={view===v.id?'active':''}><v.icon size={17}/>{v.label}</button>)}</nav></aside>
    <main id="main-content"><section className="intro"><div><div className="eyebrow">AN OPEN MAP OF CONTINUOUS LANGUAGE GENERATION</div><h1>Continuous dLLM <span>Atlas</span></h1><p>沿时间读懂研究，沿技术路线追踪方法演进。</p></div><div className="intro-stats"><div><strong>{corePapers.length}</strong><span>核心论文</span></div><div><strong>{groups.length}</strong><span>研究方向</span></div><div><strong>{relations.length}</strong><span>演化关系</span></div></div></section>
    <details className="concept-note"><summary><span className="concept-dot"/> 什么是 Continuous dLLM？<span className="concept-preview"> 连续的是生成状态，而不只是时间。</span><ChevronDown size={15}/></summary><div className="concept-grid"><p><strong>Continuous-state</strong>在实数 embedding、latent、连续 categorical 表示或 analog bits 中迭代去噪，最终通过 decoder 映射为 token。</p><p><strong>Discrete-state</strong>在 token / MASK 等离散状态之间恢复文本。连续时间训练目标或实数 hidden state 本身不意味着连续状态生成。</p><p><strong>Token-level / latent</strong>逐 token 表示和 encoder 潜变量可以交叉；latent 不一定压缩，也不一定是 VAE。扩散并行不保证 decoder 并行。</p></div></details>
    <div className="section-heading"><div><div className="eyebrow">{String(views.findIndex(v=>v.id===view)+1).padStart(2,'0')} / EXPLORE</div><h2>{activeView.label}</h2></div>{view!=='daily-brief'&&<label className="context-toggle"><input type="checkbox" checked={context} onChange={e=>setContext(e.target.checked)}/>包含离散背景 <span>{papers.length-corePapers.length}</span></label>}</div>
    {view!=='daily-brief'&&<><div className="filter-bar"><label className="topic-select"><span className="sr-only">研究方向</span><select aria-label="研究方向" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">全部技术路线</option>{groups.map(g=><optgroup key={g.id} label={g.label}><option value={g.id}>{g.label} · 全部</option>{categories.filter(c=>c.parent_id===g.id).map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</optgroup>)}</select></label><label className="search-box"><Search size={17}/><input aria-label="搜索论文" placeholder="搜索论文、作者、研究问题…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="清除搜索" onClick={()=>setQuery('')}><X size={15}/></button>}</label><label><span className="sr-only">年份</span><select aria-label="年份" value={year} onChange={e=>setYear(e.target.value)}><option value="all">所有年份</option>{years.map(y=><option key={y} value={y}>{y}</option>)}</select></label><label><span className="sr-only">State space</span><select aria-label="State space" value={state} onChange={e=>setState(e.target.value)}><option value="all">State space</option>{[...new Set(papers.map(p=>p.state_space))].filter(Boolean).map(s=><option value={s!} key={s}>{readable(s)}</option>)}</select></label><label><span className="sr-only">Inference focus</span><select aria-label="Inference focus" value={focus} onChange={e=>setFocus(e.target.value)}><option value="all">Inference focus</option>{[...new Set(papers.map(p=>p.inference_focus))].filter(Boolean).map(s=><option value={s!} key={s}>{readable(s)}</option>)}</select></label><button className="reset" onClick={reset}>重置</button></div>
    <div className="results-line"><span>{category==='all'?'全部研究方向':categoryById[category]?.label} <span className="muted">/ {filtered.length} 篇论文</span></span><span className="muted">{context?'包含独立标注的离散背景':'仅连续 / 混合研究'} · 多标签分类</span></div></>}
    {view==='daily-brief'&&<DailyBrief/>}
    {view==='research-map'&&<><ResearchMap items={filtered} category={category} open={open} dark={dark}/><div className="direction-legend">{groups.map(g=><button key={g.id} onClick={()=>setCategory(category===g.id?'all':g.id)} className={category===g.id?'active':''}><i style={{background:colorFor(g.id)}}/>{g.label}</button>)}</div></>}
    {view==='database'&&<div className="database-wrap"><table><caption className="sr-only">论文数据库，按最早公开年份降序排列</caption><thead><tr><th>论文 / RESEARCH</th><th>YEAR / VENUE</th><th>STATE SPACE</th><th>分类 / CATEGORIES</th><th>LINKS</th></tr></thead><tbody>{[...filtered].sort((a,b)=>(b.year??0)-(a.year??0)||name(a).localeCompare(name(b))).map(p=><tr key={p.id}><td><button className="paper-name" onClick={()=>open(p)}>{name(p)}<ArrowUpRight size={15}/></button><p className="table-title">{p.title}</p><span className={!p.verified?'uncertain':'muted'}>{p.verified?'核心已核实':'待核实'} · {p.pending_verification.length} 条核实备注{p.scope==='context_only'?' · 离散背景':''}</span></td><td><strong>{text(p.year)}</strong><p>{text(p.venue)}</p><small>{statusLabel(p)}</small></td><td>{readable(p.state_space)}</td><td><div className="table-tags">{p.categories.map(c=><button key={c} onClick={()=>setCategory(c)} style={{borderLeftColor:colorFor(c)}}>{categoryById[c]?.label??c}</button>)}</div></td><td><PaperLinks p={p}/></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty"><Search/><h3>没有匹配的论文</h3><p>尝试其他关键词，或清除筛选条件。</p><button onClick={reset}>重置筛选</button></div>}</div>}
    {!['research-map','database','daily-brief'].includes(view)&&(Extra?<Extra view={view} items={filtered} open={open}/>:<div className="empty" role="status">正在载入模块…</div>)}
    <footer className="site-footer"><span>Continuous dLLM Atlas <span className="muted">/ Research, with provenance.</span></span><span>N/A = 未确认 · 核心核实 ≠ 实验复现</span></footer></main></div>{selected&&<PaperDetail p={selected} close={()=>setSelected(null)} open={open}/>}</>
}
