import { useState } from 'react'
import briefData from '../data/briefs.json'
type Item={id:string;kind:string;title:string;url:string;date:string;summary:string;reason:string;systems_signal:boolean;review_status:string}
type Feed={generated_at:string|null;window_days:number;sources:{name:string;url:string;status:string;error?:string;count:number}[];items:Item[]}
const feed=briefData as Feed
export default function DailyBrief(){
 const [kind,setKind]=useState('all');const [query,setQuery]=useState('')
 const items=feed.items.filter(i=>(kind==='all'||(kind==='systems'?i.systems_signal:i.kind===kind))&&`${i.title} ${i.summary}`.toLowerCase().includes(query.toLowerCase()))
 return <div className="brief-page"><div className="view-introduction"><h3>最近值得进一步阅读的线索</h3><p>每天检索 Continuous dLLM 相关预印本，并跟踪已收录官方 GitHub 仓库的发布和提交。自动匹配结果尚未经过人工审阅，不计入论文库，也不代表已验证的性能改进。</p></div><div className="brief-status"><span>最近运行：{feed.generated_at?new Date(feed.generated_at).toLocaleString('zh-CN'):'尚未运行'}</span><span>回看 {feed.window_days} 天 · 每天北京时间 09:17 计划更新</span></div><p className="story-caption">GitHub 定时任务可能延迟。Systems 为关键词线索，不等同于已确认的系统贡献；仓库提交可能只是文档维护。</p><div className="brief-controls"><div className="segmented">{[['all','全部'],['paper','论文'],['github','GitHub'],['systems','Systems 线索']].map(([id,label])=><button key={id} className={kind===id?'active':''} onClick={()=>setKind(id)}>{label}</button>)}</div><input aria-label="搜索简报" placeholder="搜索最近动态…" value={query} onChange={e=>setQuery(e.target.value)}/></div><details className="brief-sources"><summary>来源健康状态 · {feed.sources.filter(s=>s.status==='ok').length} / {feed.sources.length} 成功</summary>{feed.sources.map(s=><p key={s.name}><a href={s.url} target="_blank" rel="noreferrer">{s.name}</a> · {s.status==='ok'?`${s.count} 条候选`:`读取失败：${s.error??'未知错误'}（保留窗口内旧记录）`}</p>)}</details><div className="brief-list">{items.map(i=><article key={i.id}><div className="card-meta"><time>{i.date.slice(0,10)}</time><span>{i.kind==='paper'?'预印本线索':'仓库动态'} · 待核实</span>{i.systems_signal&&<span>Systems 关键词</span>}</div><h3><a href={i.url} target="_blank" rel="noreferrer">{i.title} ↗</a></h3><p>{i.summary}</p><small>{i.reason}</small></article>)}</div>{!items.length&&<div className="empty">{feed.sources.some(s=>s.status!=='ok')?'部分来源读取失败；当前没有匹配记录，请查看来源状态。':'当前窗口或筛选下没有匹配线索。'}<p>这不代表相关领域没有新进展。</p></div>}</div>
}
