import { useState } from 'react'
import { ArrowDown, ArrowUpRight, ChevronDown, Cpu, Gauge, Layers, Network } from 'lucide-react'
import { type Paper, categories, groups, name, colorFor, matchesCategory, readable, text, hasEfficiency, statusLabel } from './data'
import { PaperCard, PaperLinks } from './App'

type Props = {view:string;items:Paper[];open:(p:Paper)=>void}
const axes = [{id:'algorithmic',label:'Algorithmic',subtitle:'减少迭代与生成工作量',icon:Gauge},{id:'architecture',label:'Architecture',subtitle:'减少单步算术与表示成本',icon:Layers},{id:'systems',label:'Systems evidence',subtitle:'GPU runtime / memory 实测',icon:Cpu}]
function Efficiency({items,open}:Omit<Props,'view'>){
  const [axis,setAxis]=useState('algorithmic')
  const counts = Object.fromEntries(axes.map(a=>[a.id,items.filter(p=>hasEfficiency(p,a.id)).length]))
  const selected=items.filter(p=>hasEfficiency(p,axis))
  return <><div className="efficiency-thesis"><div><span className="eyebrow">TWO DIFFERENT QUESTIONS</span><h3>更少的步骤，还是更快的每一步？</h3><p>降低 NFE / sampling steps 是算法改进；GPU latency、kernel、memory 与 serving 是系统成本。架构改进独立列出，避免将理论复杂度直接当作系统加速。</p></div><div className="cost-equation"><span>Generation cost</span><strong>∑ denoiser calls</strong><span>+ decoder + runtime + scheduling</span></div></div><div className="axis-tabs" role="tablist" aria-label="效率分类">{axes.map(a=><button role="tab" aria-selected={axis===a.id} aria-controls="efficiency-results" key={a.id} onClick={()=>setAxis(a.id)} className={axis===a.id?'active':''}><a.icon size={22}/><div><strong>{a.label}</strong><small>{a.subtitle}</small></div><b>{counts[a.id]}</b></button>)}</div><p className="small-note">按 efficiency_mechanism 的非空证据分组，允许重叠；不会仅凭 “systems.algorithmic” 分类推断减少 NFE。</p>
    <div id="efficiency-results" role="tabpanel" aria-label={axes.find(a=>a.id===axis)?.label} className="efficiency-results">{selected.length?selected.map(p=><article className="efficiency-row" key={p.id}><div><button className="paper-name" onClick={()=>open(p)}>{name(p)}<ArrowUpRight size={16}/></button><small>{text(p.year)} · {statusLabel(p)}</small><PaperLinks p={p}/></div><div><span className="eyebrow">MECHANISM</span><p>{text(p.efficiency_mechanism?.[axis])}</p><span className="eyebrow">EVALUATION METRICS</span><p className="muted">{text(p.evaluation_metrics)}</p>{p.systems_evidence&&axis==='systems'&&<div className="measurement-note"><strong>{text(p.systems_evidence.hardware)} · {text(p.systems_evidence.precision)} · {text(p.systems_evidence.nfe)} NFE</strong><p>Data: {text(p.systems_evidence.data)}</p><p>Excludes: {text(p.systems_evidence.excludes)}</p><p>{text(p.systems_evidence.limitations)}</p></div>}<details className="inline-notes"><summary>{p.pending_verification.length} 条核实备注<ChevronDown size={14}/></summary><ul>{p.pending_verification.map((s,i)=><li key={i}>{s}</li>)}</ul></details></div></article>):<div className="empty">当前筛选下没有该效率轴的证据记录。</div>}</div><div className="interpretation-note"><strong>比较前先对齐实验条件。</strong><p>NFE 不一定等于 sampling steps。需要同时检查硬件、精度、batch、序列长度、guidance、decoder、生成质量与多样性。现有数据未提供统一结果表，因此不生成速度排行榜。</p></div></>
}
function Timeline({items,open}:Omit<Props,'view'>){
  const ys=[...new Set(items.map(p=>p.year))].sort((a,b)=>(a??0)-(b??0))
  return <><div className="view-introduction"><h3>研究如何沿时间展开</h3><p>按首次公开年份排列；正式发表年份独立标注。年份相邻不意味着方法继承，关系请在 Research Map 中查看。</p></div><div className="timeline">{ys.map(y=>{const entries=items.filter(p=>p.year===y).sort((a,b)=>(a.first_submission_date??'9999').localeCompare(b.first_submission_date??'9999')||name(a).localeCompare(name(b)));return <section className="timeline-year" key={text(y)}><div className="year-marker"><h3>{text(y)}</h3><span>{entries.length} papers</span><ArrowDown size={17}/></div><div className="year-content"><div className="timeline-directions">{groups.filter(g=>entries.some(p=>matchesCategory(p,g.id))).map(g=><span key={g.id} style={{color:colorFor(g.id)}}><i style={{background:colorFor(g.id)}}/>{g.label}</span>)}</div><div className="timeline-papers">{entries.map(p=><article key={p.id}><div className="timeline-date">{p.first_submission_date??'N/A · 精确日期待核实'}</div><button className="paper-name" onClick={()=>open(p)}>{name(p)} <ArrowUpRight size={15}/></button><p>{p.main_contribution??'N/A'}</p><div className="card-meta"><span>{text(p.venue)} · {statusLabel(p)} · 正式发表年 {text(p.publication_year)}</span>{!p.verified&&<span className="uncertain">待核实</span>}{p.scope==='context_only'&&<span>离散背景</span>}</div></article>)}</div></div></section>})}</div></>
}
function Directions({items,open}:Omit<Props,'view'>){return <><div className="view-introduction"><h3>从问题进入文献</h3><p>展开子方向查看所有匹配论文。一篇研究可以同时贡献于表示、训练、采样与解码接口。</p></div><div className="direction-sections">{groups.map((g,i)=>{const entries=items.filter(p=>matchesCategory(p,g.id));return <section className="direction-section" key={g.id}><header><span className="direction-number" style={{color:colorFor(g.id)}}>{String(i+1).padStart(2,'0')}</span><div><h3>{g.label}</h3><p>{g.research_question}</p></div><b>{entries.length}<small>papers</small></b></header>{categories.filter(c=>c.parent_id===g.id).map(c=>{const sub=entries.filter(p=>matchesCategory(p,c.id));return <details key={c.id}><summary><i style={{background:colorFor(c.id)}}/><strong>{c.label}</strong><span>{sub.length} 篇</span><ChevronDown size={16}/></summary><p className="direction-description">{c.description}</p>{sub.length?<div className="paper-card-grid">{sub.map(p=><PaperCard key={p.id} p={p} open={open}/>)}</div>:<p className="gap-note">当前筛选与数据快照下未收录匹配论文；不代表该方向不存在相关工作。</p>}</details>})}</section>})}</div></>}
function Systems({items,open}:Omit<Props,'view'>){const systemCategories=categories.filter(c=>c.parent_id==='systems'&&c.id!=='systems.algorithmic');return <><div className="view-introduction"><span className="eyebrow">EVIDENCE GAPS, NOT CLAIMS OF ABSENCE</span><h3>Systems & open areas</h3><p>相对于当前快照中的模型与采样研究，以下方向在本图谱中 relatively underexplored。收录量反映数据覆盖范围，不能用于判断整个领域是否已有工作。</p></div><div className="systems-grid">{systemCategories.map((c,i)=>{const entries=items.filter(p=>matchesCategory(p,c.id));const Icon=[Cpu,Network,Layers][i%3];return <section key={c.id} className="system-area"><div className="system-icon"><Icon size={24}/><span>{String(i+1).padStart(2,'0')}</span></div><h3>{c.label}</h3><p>{c.description}</p><div className="area-count"><strong>{entries.length}</strong><span>当前筛选下的收录论文</span></div><div className="open-label">Relatively underexplored in this atlas</div>{entries.map(p=><div className="system-paper" key={p.id}><button className="paper-name" onClick={()=>open(p)}>{name(p)}<ArrowUpRight size={15}/></button><p>{p.systems_evidence?text(p.systems_evidence.limitations):'Systems evidence: N/A'}</p></div>)}{!entries.length&&<p className="small-note">暂无可展示的证据记录。N/A 不代表不存在相关研究。</p>}</section>})}</div><div className="interpretation-note"><strong>“运行于 GPU / NPU”不等于硬件协同设计。</strong><p>少步骤、紧凑表示、denoiser-only 吞吐、固定 NFE profiling 和真实服务成本需要不同证据，不能互相替代。</p></div></>}
function Bars({title,subtitle,rows}:{title:string;subtitle:string;rows:{label:string;count:number;color?:string}[]}){const max=Math.max(1,...rows.map(r=>r.count));return <section className="stat-chart"><h3>{title}</h3><p>{subtitle}</p><div className="chart-rows">{rows.map(r=><div key={r.label} className="chart-row"><div><span>{r.label}</span><b>{r.count}</b></div><div className="bar-track"><span style={{width:`${r.count/max*100}%`,background:r.color||'var(--accent)'}}/></div></div>)}</div></section>}
function Statistics({items}:Omit<Props,'view'>){const count=(fn:(p:Paper)=>boolean)=>items.filter(fn).length;return <><div className="stat-summary"><div><span>当前论文</span><strong>{items.length}</strong><small>唯一 paper id</small></div><div><span>核心研究</span><strong>{count(p=>p.scope==='core')}</strong><small>Continuous / hybrid</small></div><div><span>离散背景</span><strong>{count(p=>p.scope==='context_only')}</strong><small>Context only</small></div><div><span>存在核心核实冲突</span><strong>{count(p=>!p.verified)}</strong><small>verified = false</small></div></div><p className="small-note">统计跟随当前筛选。分类和效率轴允许重叠；“核心已核实”不表示所有字段完整或实验已经复现。</p><div className="statistics-grid"><Bars title="Publication timeline" subtitle="按最早已核实年份计数" rows={[...new Set(items.map(p=>p.year))].sort((a,b)=>(a??0)-(b??0)).map(y=>({label:text(y),count:count(p=>p.year===y)}))}/><Bars title="Research directions" subtitle="多标签计数，同一论文可进入多个方向" rows={groups.map(g=>({label:g.label,count:count(p=>matchesCategory(p,g.id)),color:colorFor(g.id)}))}/><Bars title="State space" subtitle="来自 state_space 字段，不以 continuous-time 替代" rows={[...new Set(items.map(p=>p.state_space))].map(s=>({label:readable(s),count:count(p=>p.state_space===s)}))}/><Bars title="Efficiency evidence" subtitle="基于非空机制；架构与 GPU 证据单独统计" rows={[...axes.map(a=>({label:a.label,count:count(p=>hasEfficiency(p,a.id))})),{label:'无已记录的效率机制',count:count(p=>!axes.some(a=>hasEfficiency(p,a.id)))}]}/><Bars title="Publication status" subtitle="仅陈述数据中已确认的发表状态" rows={[...new Set(items.map(p=>p.publication_status))].map(s=>({label:readable(s),count:count(p=>p.publication_status===s)}))}/><Bars title="Data completeness" subtitle="已记录的字段，不代表额外核实或实验复现" rows={[{label:'Paper URL',count:count(p=>Boolean(p.paper_url))},{label:'Code URL',count:count(p=>Boolean(p.code_url))},{label:'Project URL',count:count(p=>Boolean(p.project_url))},{label:'Model scale',count:count(p=>Boolean(p.model_scale))},{label:'存在核实备注',count:count(p=>p.pending_verification.length>0)}]}/></div></>}
export default function Sections({view,items,open}:Props){if(!items.length&&view!=='systems'&&view!=='directions'&&view!=='statistics')return <div className="empty">当前筛选没有匹配论文。请调整上方筛选。</div>;switch(view){case'timeline':return <Timeline items={items} open={open}/>;case'directions':return <Directions items={items} open={open}/>;case'efficiency':return <Efficiency items={items} open={open}/>;case'systems':return <Systems items={items} open={open}/>;case'statistics':return <Statistics items={items} open={open}/>;default:return null}}
